#Week 2 Assignment - Math with Python Bridge
## Christian Thieme 
## 1-10-2020


### 1.  Write a Python program to compute the eigenvalues and right eigenvectors of a given square array:


In [1]:
import numpy as np 
from numpy import array
from numpy import linalg 

print("The following program will compute the eigenvalues and right eigenvectors of a square matrix.")  
R = int(input("How many rows are in your matrix?:")) 
C = int(input("How many columns are in your matrix?:")) 

#Check if the matrix is square - if not square - error and exit the program
if R != C: 
  print("Error: This program only works for square matrices, please re-run the program and enter a square matrix")
  exit  
else:
  # Input to enter a matrix must come in the form of 1 2 3 4 5 6 7 8 9 and then will be formatted to matrix using reshape below   
  print("On a single line, enter all values from the matrix separated by a space:  ") 

  #takes user input and splits and converts to int, then stores in list
  entries = list(map(int, input().split())) 
    
  #converting list to matrix from list
  matrix = np.array(entries).reshape(R, C) 
  print("----------------------------------------------------------") 
  print("You have entered the following matrix: ")
  print(matrix)
  print("----------------------------------------------------------")
  #calculating eigenvalues and right eigenvectors
  values, vectors= linalg.eig(matrix)
  print("The eigenvalue/s for the above matrix are:\n {0}".format(values))
  print("----------------------------------------------------------")
  print("The right eigenvector/s normalized to unit length are:\n {0}".format(vectors))
  

The following program will compute the eigenvalues and right eigenvectors of a square matrix.
How many rows are in your matrix?:3
How many columns are in your matrix?:3
On a single line, enter all values from the matrix separated by a space:  
1 2 3 4 5 6 7 8 9
----------------------------------------------------------
You have entered the following matrix: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
----------------------------------------------------------
The eigenvalue/s for the above matrix are:
 [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
----------------------------------------------------------
The right eigenvector/s normalized to unit length are:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### 2.  Write a Python program to compute the factor of a given array by Singular Value Decomposition:


In [2]:
print("The following program will compute the Singular Value Decomposition of any matrix.") 
# Have to get the rows and columns of the matrix in order to reshape the input from the user.  
R = int(input("How many rows are in your matrix?:")) 
C = int(input("How many columns are in your matrix?:")) 

print("On a single line, enter all values from the matrix separated by a space:  ") 

#takes user input and splits and converts to int, then stores in list
entries = list(map(int, input().split())) 
  
#converting list to matrix 
matrix = np.array(entries).reshape(R, C) 
print("----------------------------------------------------------") 
print("You have entered the following matrix: ")
print(matrix)
print("----------------------------------------------------------")
#calculation of SVD - broken into three outputs: U, s, V
U, s, V = linalg.svd(matrix)
print("The factor of the above entered matrix is: ")
print("----------------------------------------------------------")
print("U = {0}".format(U))
print("----------------------------------------------------------")
print("s = {0}".format(s))
print("----------------------------------------------------------")
print("V = {0}".format(V))
  

The following program will compute the Singular Value Decomposition of any matrix.
How many rows are in your matrix?:3
How many columns are in your matrix?:2
On a single line, enter all values from the matrix separated by a space:  
1 2 3 4 5 6
----------------------------------------------------------
You have entered the following matrix: 
[[1 2]
 [3 4]
 [5 6]]
----------------------------------------------------------
The factor of the above entered matrix is: 
----------------------------------------------------------
U = [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
----------------------------------------------------------
s = [9.52551809 0.51430058]
----------------------------------------------------------
V = [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


### 3.  Write a Python program to compute the determinant of an array.


###### Below is a program I wrote to calculate the determinant of a square matrix WITHOUT utilizing the built in linalg.det(A) function. I utilized the fact that you can find the determinant based on the product of the diagonal values of a upper triangle matrix. The tricky part was figuring out how to factor in the negation changes when there was a permutation of the rows, but I was able to figure that out by counting the changes to the permuation matrix. 

In [3]:
#The below is a program not utilizing the det built in funtionality in scipy
import scipy.linalg as la

print("The following program will compute the determinant of a square matrix.")  
R = int(input("How many rows are in your matrix?:")) 
C = int(input("How many columns are in your matrix?:")) 

#this program only works for square matrices, so the below code checks to make sure columns and rows match
if R != C: 
  print("Error: This program only works for square matrices, please re-run the program and enter a square matrix")
  exit  
else:
  print("On a single line, enter all values from the matrix separated by space:  ") 

  #takes user input and splits and converts to int, then stores in list
  entries = list(map(int, input().split())) 
    
  #converting list to matrix 
  matrix = np.array(entries).reshape(R, C) 
  print("----------------------------------------------------------") 
  print("You have entered the following matrix: ")
  print(matrix)
  print("----------------------------------------------------------")
  #the below line calculates the upper triangle matrix
  u, piv = la.lu_factor(matrix)
  # I get a list of the diagonal values from the right upper matrix with the below
  diagonal = np.diag(u)
  print("The diagonal values of the above Upper Trianle matrix are:\n {0}".format(diagonal))
  print("----------------------------------------------------------")
  #the determinant is the product of the values of the diagonal list from above, the below calculates that product.  
  determinant = np.prod(diagonal)
  #The sign changes on the determinant if there were permutations to the matrix during the conversion to upper triangular form. If rows are swapped, it negates the determinant. However, if a two rows are swapped
  #the negation negates itself. The following code counts the permutations and correctly determines the sign (+/-) for the determinant based on the indices of the permutation matrix. 
  if determinant == 0:
    print("The determinant for this matrix is: 0. This means that the matrix is not invertible and all the columns are not linearly independent.")
  else:
    count = 0
    for i in range(len(piv)):
      if i != piv[i]:
        count +=1
      else: 
        next
#Final calculation with correct sign for determinant.   
  print("The determinant of the matrix is: {0}".format(round(determinant*(-1)**count), 0))
    


The following program will compute the determinant of a square matrix.
How many rows are in your matrix?:4
How many columns are in your matrix?:4
On a single line, enter all values from the matrix separated by space:  
-2 3 1 4 1 1 7 2 0 0 -1 2 -3 2 1 1
----------------------------------------------------------
You have entered the following matrix: 
[[-2  3  1  4]
 [ 1  1  7  2]
 [ 0  0 -1  2]
 [-3  2  1  1]]
----------------------------------------------------------
The diagonal values of the above Upper Trianle matrix are:
 [-3.          1.66666667  7.          1.85714286]
----------------------------------------------------------
The determinant of the matrix is: 65.0
